version: '3.8'

services:
  guildmaster:
    image: guildmaster
    build:
      context: .
      dockerfile: ./Dockerfile
  mongodb:
    image: mongo:4.4
    volumes:
      - db:/data/db
    ports:
      - 27016:27017

volumes:
  db:
